README.rst
src/mattermostdriver/client.py
src/mattermostdriver/endpoints/files.py

In order for `requests` to format the request data as `multipart/form-data`, the `files` parameter has to be used. The parameter has been implemented in `Client` `make_request` and `post` and in the `Files` endpoint, where the parameter `data` has been replaced by `channel_id` and `files`.
I provided an example of how to upload a file and mention it in a post.
I also replaced usage of `json` in `clients.py`, since it is easier available from `requests` response object.

Upload file, Examples, minor touch-up

---

src/mattermostdriver/driver.py

If you want to use a non-standard way to login into Mattermost, you need to subclass the `Client` and `Websocket`classes (and maybe even the `Driver`). 
However, `Driver` will not use your custom subclasses. A clean way to inject them into the Mattermost `Driver` would be to just pass them to `Driver()` and `Driver.init_websocket()`.

Make Client and Websocket classes customizable

---

src/mattermostdriver/client.py

The exception ResourceNotFound is already present and documented, but
the implementation forget to handle 404 errors thus propagating a raw
HTTPError.

Handle HTTP 404 errors as ResourceNotFound

---

src/mattermostdriver/driver.py

We still need to use the temporary token generated by a login/password authentication to actually logout. So I moved the clean up after the call to `logout_user()`

Fix logout by loging out before cleaning up

---

src/mattermostdriver/client.py
src/mattermostdriver/exceptions.py

I guess fixes #31.
When that happens fallback to text.
I also added the `MethodNotAllowed` exception, which is returned with an empty body, for example on a `POST` with a wrong `basepath` (`POST /api/vv4`) but maybe we want to limit ourselves to Mattermost JSON errors (not all HTTP)?.

Handle non-JSON responses

---

src/mattermostdriver/driver.py

While attempting to modify a user's status I noticed the property for accessing the endpoint didn't exist on the `Driver` class but did exist under the deprecated api property. I'm also adding the roles/commands properties too while I'm here so the properties the `Driver` class should now be in sync with what's available in the deprecated api property.

Add missing status, roles and commands properties

---

README.rst

missing ',' at line 70, which mage the example code invalid

added ','  to make json valid

---

docs/mmDriverTokenAuthExample.py
src/mattermostdriver/client.py
src/mattermostdriver/driver.py

I want to use .netrc to get an access token instead of a login/pwd combination. At present, when mmdriver finds the host in .netrc, it assumes basic authentication with login/pwd from there. 
This PR modifies the behaviour and allows the user to pass  in an Auth object which can be used in a more flexible way, e.g. setting  up the Authorization header with a "Bearer <token>" value.

fix to use token from .netrc

---

README.rst
setup.py
src/mattermostdriver/driver.py
src/mattermostdriver/websocket.py

* Drop Python 3.4 support
Python 3.4 reached EOL on March 18, 2019:
https://python.org/downloads/release/python-3410
* Support Python 3.8
* Python 3.8.0 has been released on October 14, 2019
https://python.org/downloads/release/python-380
* Fix `@coroutine` deprecation warnings
```
DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
```
https://docs.python.org/3.8/library/asyncio-task.html#asyncio.coroutine
https://docs.python.org/3.8/reference/compound_stmts.html#coroutine-function-definition
Note: Although everything loads perfectly, I have not truly tested the websocket part, someone else will have to confirm that it still works as intended.
Closes #51

Support python 3.8

---

src/mattermostdriver/websocket.py

For current Mattermost version, the websocket driver is telling that the websocket authentication has failed but then it works OK. Fix is to check for different keys in the welcome message.

Fix check for authentication failed

---

src/mattermostdriver/driver.py
src/mattermostdriver/websocket.py

Since `Driver.init_websocket` starts an infinite loop, there is currently no way to cleanly shutdown the driver. This PR adds a `self._alive` flag that can be toggled with a `disconnect` function to break out of the event loop.

Add `Driver.disconnect` function

---

CHANGELOG.rst
setup.py
src/mattermostdriver/version.py

Requirement changes
- websocket bumped from 6.0 to 8.1
- requests bumped from 2.20.0 to 2.25.1
Added
- Add Driver.disconnect function #80
- Raise errors from None to reduce traceback noise #69
Fixes
- Correct url for role by name #78
- Add oldest unread endpoint #76
Documentation:
- Improve documentation about verify #64
Thanks a lot to @jneeven for his contribution!

chore: Bump version to 7.2.0

---

README.rst
src/mattermostdriver/driver.py
src/mattermostdriver/websocket.py

When connectivity to the Mattermost server is lost and restored at a later time, the driver fails to re-establish a websocket connection, usually raising a `ConnectionClosedError` exception. This PR resolves that issue with a change to `Websocket.connect()` so that it will continually attempt to re-establish a websocket connection. 
Update: I have merged a PR from @attzonko that makes this optional (default off), and adds a new option for the retry interval.

Re-establish websocket after connectivity loss

---

.github/workflows/pythonpackage.yml
README.rst
setup.py

Release 7.2.0 contained a breaking change when it upgraded `websocket` to 8+, which dropped support Python 3.5:
https://websockets.readthedocs.io/en/stable/project/changelog.html#id19
Python 3.5 has also reached EOL in September 2020:
https://www.python.org/dev/peps/pep-0478/

Drop Python 3.5 support explicitly

---

README.rst

I was working last days with Mattermost bot and realised that neither standard upload example and neither `make_request` upload work.
Here is an example how it fails and how it works after this fix:
```
>>> data={'channel_id': '9cygtgktgi8tdcnhct4dk9heto'}
>>> files = {'files': (pdf_name, open(pdf_file))};    file_id_2 = mm.client.make_request('post', '/files', data=data, files=files)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.9/site-packages/mattermostdriver/client.py", line 157, in make_request
response = request(
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in …
```

fixed file upload - UnicodeDecodeError: 'utf-8' codec can't decode byte in position 342: invalid start byte

---

.gitignore
requirements.txt
setup.py
src/mattermostdriver/__init__.py
src/mattermostdriver/client.py
src/mattermostdriver/driver.py
src/mattermostdriver/exceptions.py

I chose `httpx` because it comes with sync and async interfaces, its close to `requests` api and supports http2. 
The `Driver` and `Client` classes still function the same as they did. 
The new `AsyncDriver` and `AsyncClient` are completely asyncio friendly.   The `AsyncDriver.init__websocket()` no longer does eventloop bootstrapping, and instead leaves it up to the caller who is now assumed to be completely async aware.
A very simple bot using the new interface. 
```
async def event_handler(driver, me, raw):
payload = json.loads(raw)
print(payload)
event = payload.get('event')
if event:
data = message.get('data')
if event == "posted":
where = data['channel_display_name']
sender_name = data['sender_name']
post = json.loads(data['post'])
msg = post["message"]
print(f"[{where}] …
```

Move to httpx over requests to provide a 100% async driver. 

---

src/mattermostdriver/websocket.py

Fixes compatibility with Mattermost 6.3.0
Without this I was getting 1006 error when calling init_websocket after upgrade to mattermost 6.3.0

FIX: Removed encode("utf-8") from websocket authentication

---

CHANGELOG.rst
requirements.txt
setup.py
src/mattermostdriver/client.py
src/mattermostdriver/driver.py
src/mattermostdriver/websocket.py

Many corporations require the use of a proxy server for logging etc. - We needed this so I added it.
- Add a new 'proxy' option
- Move from websockets to aiohttp due to no http proxy support: https://github.com/aaugustin/websockets/issues/364
- Format 'proxy' option into the dictionary httpx requires for 'all://'
- Updated requirements / setup.py
- Updated CHANGELOG

Add http proxy support

---

src/mattermostdriver/websocket.py

`.encode('utf8')` doesn't seem to work with mattermost 6.3.0

fix: use send_str instead of send_bytes

---

README.rst

I noticed that one rogue comma and one missing comma were messing up the highlighting in README, so I fixed them.

Fixing commas in README
